
class Config:
    MIN_DELIVERY_COST = 400
    FRAGILE_DELIVERY_COST = 300

    MAX_DELIVERY_LOAD_RATE = 3
    MIN_DELIVERY_LOAD_RATE = 0.8

    MAX_DELIVERY_DISTANCE = 1000
    MAX_DELIVERY_DISTANCE_FOR_FRAGILE_ITEMS = 30